### ISSUE TITLE
Society Manage Credit

### ISSUE THREAD

**Issue by harveyqiu** [JeekStudio/StudentPlatform#71]
@nichujie CreditReceivers是怎么一个用法
社团部 先设定好 学年和 学期
然后 打开一个能够 填写学分表格的申请 的选项开关？
然后社团开始填写 会获得学分的成员名单？

**Comment by nichujie** [comment]
先是社团部settings里面设置当前的学年和学期，然后credit receivers应该是设置完之后自动生成了，每个学期所有active社团都生成一个（可以多个按钮干这个事）。

然后社长就可以在学分管理里面选择把学分给谁（就那个transfer），获取到和修改的都是当前学期的credit receivers。

社团部要统计就去后台导出表格，要停止让他们修改就把学期更新到下学期即可。

**Comment by harveyqiu** [comment]
应该加一个开关 而不是 通过改 学期 来处理 社团填写receivers 的权限

**Comment by nichujie** [comment]
了解

**Comment by nichujie** [comment]
现在model里面新增了available(bool)之后，前端可以考虑在false的时候disable那个transfer，然后在404的时候显示“社团部还未设置本学期学分”

**Comment by harveyqiu** [comment]
并不是理想的实现方式

**Comment by nichujie** [comment]
so what's the better solution

**Comment by harveyqiu** [comment]
这个我自己写

**Comment by harveyqiu** [comment]
与 #113 重复
