### ISSUE TITLE
StudentMiniSerializer

### ISSUE THREAD

**Issue by nichujie** [JeekStudio/StudentPlatform#77]
Q1. 里面的qq是用来干啥的
Q2. 是否要再带个username（学号）的field便于展示，例如：20151333 Nichujie
<img width="731" alt="2019-02-13 11 59 46" src="https://user-images.githubusercontent.com/17191827/52725105-7ea3e100-2feb-11e9-81be-7d54e5b92346.png">

**Comment by harveyqiu** [comment]
QQ用来线上联系人 什么的

**Comment by harveyqiu** [comment]
学号展示出来有什么用 ， 你靠学号找人？
