### ISSUE TITLE
抽象出sb和sm的layout

### ISSUE THREAD

**Issue by harveyqiu** [JeekStudio/StudentPlatform#80]
抽象出sb和sm的layout

**Comment by nichujie** [comment]
这是啥意思，是指长得一样吗

**Comment by harveyqiu** [comment]
好像有个的后台还没改掉

**Comment by harveyqiu** [comment]
现在的Layout有个问题
就是顶部那个header我用的是flex
不要用flex了
右边的那个用户名的Menu弄个float: right
然后让左边的那个面包屑能够垂直居中
